kind: Deployment
apiVersion: apps/v1
metadata:
  name: kwetter-web-app
  labels:
    k8s-app: kwetter-web-app
spec:
  selector:
    matchLabels:
      app: kwetter-web-app
  template:
    metadata:
      labels:
        app: kwetter-web-app
    spec:
      containers:
        - name: kwetter-web-app
          image: eu.gcr.io/kwetter-web-app
          ports:
            - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: kwetter-web-app
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: kwetter-web-app
