name: pipeline

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Publish Docker Image to Google Container Registry
        uses: kurkop/push-docker-gcr@v1.2.2
        with:
          docker_image_name: kwetter-web-app
          docker_image_tag: latest
          docker_context: .
          gcr_host: eu.gcr.io
          gcr_project_id: ${{ secrets.GKE_PROJECT_ID }}
          gcr_service_key: ${{ secrets.GCR_SA_KEY }}

      - name: Deploy
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: kwetter
          ZONE_NAME: europe-west4-a
        with:
          args: apply -f ./deployment.yaml
